### ISSUE TITLE
NoClassDefFoundError starting version 4.1.0

### ISSUE THREAD

**Issue by amanda45762** [hawtio/hawtio#3669]
Hello, I am trying to get hawtio-war-4.1.0.war (or later) to work with any tomcat version. Want to use 4.1.0 because it includes a code fix I needed. I see in the[ hawtio docs ](https://hawt.io/docs/versions.html) that hawtio 4.0.x uses JEE9. What JEE does 4.1.x use?

I tried tomcat 9.0.93 where I got error:
```
SEVERE [main] org.apache.catalina.core.StandardContext.listenerStart Error configuring application listener of class [io.hawt.HawtioContextListener]
        java.lang.NoClassDefFoundError: jakarta/servlet/ServletContextListener
```
I then tried tomcat 10.0.x,10.1.x, and 11.0.x ([docs on compatibility with different JEE's here](https://tomcat.apache.org/whichversion.html)) but got the below error:
```
16:32:40.925 [main] WARN  o.eclipse.jetty.webapp.WebAppContext - Failed startup of context o.e.j.w.WebAppContext@24b52d3e{hawtio,/hawtio,file:///Users/xxxxx/.hawtio/tmp/webapp/,UNAVAILABLE}{/Users/xxxxx/camel/hawtio/hawtio-war-4.0-beta-1.war}
java.lang.NoClassDefFoundError: jakarta/servlet/ServletContextListener
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:555)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
	at org.eclipse.jetty.webapp.WebAppClassLoader.findClass(WebAppClassLoader.java:637)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:515)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.eclipse.jetty.util.Loader.loadClass(Loader.java:64)
	at org.eclipse.jetty.servlet.BaseHolder.doStart(BaseHolder.java:89)
	at org.eclipse.jetty.servlet.ListenerHolder.doStart(ListenerHolder.java:72)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:369)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1457)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1422)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:916)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:423)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:387)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at io.hawt.embedded.Main.run(Main.java:116)
	at io.hawt.embedded.Main.run(Main.java:78)
	at io.hawt.embedded.Main$run$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
	at camelpack.Application.main(Application.groovy:31)
Caused by: java.lang.ClassNotFoundException: jakarta.servlet.ServletContextListener
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
```
I saw in hawtio issue #3337 that hawtio 4.x uses JEE9. In the tomcat docs linked above, it seems like tomcat 10.0.x which is no longer supported is the only one that uses JEE9. Tomcat 10.1.x uses JEE10 and Tomcat 11.0.x uses JEE11. Is there any version of tomcat out there that can work with hawtio 4.1.0 or later?

**Comment by tadayosi** [comment]
You should be able to deploy Hawtio >=4.1.0 to Tomcat versions that support JEE9 or higher.
Your stacktrace suggests you're using hawtio-4.0-beta-1 and Jetty. Please check it again with Tomcat.

**Comment by amanda45762** [comment]
@tadayosi sorry i pasted the wrong error logs for 10.0.x,10.1.x, and 11.0.x. This is the errors I saw:
```
24-Oct-2024 14:45:17.909 WARNING [main] org.apache.tomcat.util.digester.SetPropertiesRule.begin Match [Server/Service/Executor] failed to set property [maxThreads] to [${catalina.tomcat.maxthreadpool}]
24-Oct-2024 14:45:17.914 WARNING [main] org.apache.tomcat.util.digester.SetPropertiesRule.begin Match [Server/Service/Executor] failed to set property [minSpareThreads] to [${catalina.tomcat.minSpareThreads}]
24-Oct-2024 14:45:17.999 WARNING [main] org.apache.tomcat.util.digester.SetPropertiesRule.begin Match [Server/Service/Connector] failed to set property [connectionTimeout] to [${catalina.tomcat.httpconnector.connectionTimeout}]
24-Oct-2024 14:45:18.000 WARNING [main] org.apache.tomcat.util.digester.SetPropertiesRule.begin Match [Server/Service/Connector] failed to set property [maxHttpHeaderSize] to [${catalina.tomcat.httpconnector.maxHttpHeaderSize}]
24-Oct-2024 14:45:18.031 SEVERE [main] org.apache.tomcat.util.digester.Digester.startElement Begin event threw exception
        java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletResponse
                at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
                at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3373)
                at java.base/java.lang.Class.getConstructor0(Class.java:3578)
                at java.base/java.lang.Class.getConstructor(Class.java:2271)
                at org.apache.tomcat.util.digester.ObjectCreateRule.begin(ObjectCreateRule.java:103)
                at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1264)
                at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:518)
                at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:183)
                at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1387)
                at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2726)
                at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
                at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
                at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
                at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
                at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
                at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
                at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
                at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1522)
                at org.apache.catalina.startup.Catalina.parseServerXml(Catalina.java:603)
                at org.apache.catalina.startup.Catalina.load(Catalina.java:693)
                at org.apache.catalina.startup.Catalina.load(Catalina.java:731)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:569)
                at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:302)
                at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:472)
        Caused by: java.lang.ClassNotFoundException: javax.servlet.http.HttpServletResponse
                at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
                at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
                at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
                ... 27 more
24-Oct-2024 14:45:18.036 SEVERE [main] org.apache.catalina.startup.Bootstrap.main Error running command
        java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletResponse
                at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
                at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3373)
                at java.base/java.lang.Class.getConstructor0(Class.java:3578)
                at java.base/java.lang.Class.getConstructor(Class.java:2271)
                at org.apache.tomcat.util.digester.ObjectCreateRule.begin(ObjectCreateRule.java:103)
                at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1264)
                at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:518)
                at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:183)
                at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1387)
                at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2726)
                at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
                at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
                at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
                at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
                at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
                at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
                at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
                at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1522)
                at org.apache.catalina.startup.Catalina.parseServerXml(Catalina.java:603)
                at org.apache.catalina.startup.Catalina.load(Catalina.java:693)
                at org.apache.catalina.startup.Catalina.load(Catalina.java:731)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:569)
                at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:302)
                at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:472)
        Caused by: java.lang.ClassNotFoundException: javax.servlet.http.HttpServletResponse
                at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
                at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
                at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
                ... 27 more
```

**Comment by amanda45762** [comment]
I see the javax package is being used throughout the hawtio 4.x code. But according to [this user](https://stackoverflow.com/questions/64387472/servlet-5-0-jar-throws-compile-error-on-javax-servlet-but-servlet-4-0-jar-does):
The jakarta.servlet.Servlet is part of Servlet API version 5.0 which in turn is part of Jakarta EE version 9. Your servlet is actually extending from javax.servlet.Servlet which in turn is part of an older JEE version which is actually not supported by your target runtime (Tomcat 10.x).

**Comment by grgrzybek** [comment]
> I see the javax package is being used throughout the hawtio 4.x code

Where exactly?
`jakarta.servlet`:
![image](https://github.com/user-attachments/assets/f3bdbeef-3b21-429d-a4c9-fde97907155b)

`javax.servlet`:
![image](https://github.com/user-attachments/assets/c6b630c9-639c-49c3-b218-d88d9028b0c8)

**Comment by amanda45762** [comment]
@grgrzybek eg here https://github.com/hawtio/hawtio/blob/4.x/hawtio-system/src/main/java/io/hawt/jmx/JMXSecurity.java#L6
But agree that I don't see the 4.x code using javax.servlet.http.HttpServletResponse which I see in my error logs. Am I downloading the wrong hawtio 4.1 war? (See above)

**Comment by grgrzybek** [comment]
This line is about `javax.management`, not `javax.servlet`. JakartaEE is NOT about moving all `javax` packages to `jakarta`.

https://github.com/hawtio/hawtio/releases/tag/hawtio-4.1.0 is fine - I just checked it. It uses Jolokia 2 which also uses `jakarta.servlet`.

May I see your setup? Is it embedded Jetty (as in first stacktrace) or standalone Tomcat (as in second stacktrace)?

**Comment by amanda45762** [comment]
@grgrzybek here's my docker file
```
FROM amazoncorretto:17.0.12-alpine

ENV TOMCAT_MAJOR=10 \
    TOMCAT_VERSION=10.1.31

ENV CATALINA_HOME /opt/tomcat
ENV PATH ${CATALINA_HOME}/bin:$PATH
ENV TOMCAT_NATIVE_LIBDIR=$CATALINA_HOME/native-jni-lib
ENV LD_LIBRARY_PATH=$CATALINA_HOME/native-jni-lib

RUN apk -U upgrade --update && \
    apk add --no-cache bash curl openssl dhclient ttf-dejavu && \
    wget -O /tmp/apache-tomcat.tar.gz https://archive.apache.org/dist/tomcat/tomcat-${TOMCAT_MAJOR}/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz && \
    tar -C /opt -xvf /tmp/apache-tomcat.tar.gz && \
    ln -s /opt/apache-tomcat-${TOMCAT_VERSION}/ $CATALINA_HOME && \
    rm -rf $CATALINA_HOME/webapps/* && \
    rm -rf /tmp/apache-tomcat.tar.gz && \
    mkdir -p $CATALINA_HOME/logs && \
    mkdir -p $CATALINA_HOME/work && \
    chmod -R u+wxr $CATALINA_HOME && \
    addgroup -g 2000 user && \
    adduser -h $CATALINA_HOME -u 2000 -G user -s /bin/sh -D user && \
    chown -R user:user$CATALINA_HOME/ 

WORKDIR /opt/tomcat/bin
COPY *.sh ./
RUN dos2unix ./*.sh && \
    chmod +x ./s*.sh && \
    mkdir /opt/var && \
    chown -R user:user/opt/var

COPY *.xml /opt/tomcat/conf/
ADD http://<registry>/utils/jmx_patch.jar /opt/tomcat/lib/jmx_patch.jar

WORKDIR /
ENTRYPOINT []
CMD ["catalina.sh", "run"]

ADD hawtio-war-4.1.0.war /opt/tomcat/webapps/hawtio.war
ADD logback-access-1.2.3.jar /opt/tomcat/lib/logback-access-1.2.3.jar
ADD logback-core-1.2.3.jar /opt/tomcat/lib/logback-core-1.2.3.jar
ADD janino-3.1.9.jar /opt/tomcat/lib/janino-3.1.9.jar
ADD commons-compiler-3.1.9.jar /opt/tomcat/lib/commons-compiler-3.1.9.jar
COPY server.xml /opt/apache-tomcat-${TOMCAT_VERSION}/conf/server.xml
COPY web.xml /opt/tomcat/conf/web.xml
COPY logback.xml /opt/tomcat/conf/logback-access.xml
COPY ldap.conf /opt/tomcat/conf/login.conf


EXPOSE 8090

ENV APP_JVM_ARGS="-Dhawtio.authenticationEnabled=true -Dhawtio.authenticationContainerDiscoveryClasses= -Dhawtio.realm=hawtio -Djava.security.auth.login.config=$CATALINA_HOME/conf/login.conf -Dhawtio.sessionTimeout=1200 -Dhawtio.proxyAllowlist=* -Dendpoints.jolokia.sensitive=false"
```

**Comment by amanda45762** [comment]
@grgrzybek I think my issue is with logback not hawtio actually

**Comment by grgrzybek** [comment]
You add everything to `/opt/tomcat` lib - and yes - it may be logback issue.

**Comment by tadayosi** [comment]
Let me close it as the issue seems to be with logback.
