### ISSUE TITLE
Camel plugin not displaying route metrics

### ISSUE THREAD

**Issue by gdubya** [hawtio/hawtio#2311]
I have a Spring (v4.3.5) webapp (not Boot) producing a war, deployed in Tomcat. The Spring app includes Camel 2.19.0. I have included the camel-metrics component in the application and set the appropriate MetricsRoutePolicyFactory on the camelContext.

`        camelContext.addRoutePolicyFactory(new MetricsRoutePolicyFactory());
`

When I click on the "Route Metrics" tab in the Hawtio (1.5.0) Camel plugin I see the "loading icon" for a second or two before I get a message stating "This Camel context has no route metrics data." Why can't I see the metrics data in Hawtio?

**Comment by gdubya** [comment]
Ah, found a stacktrace in the response to one of the XHR requests (
http://localhost:8085/hawtio/proxy/http://localhost:8080/myApp/jolokia/?maxDepth=7&maxCollectionSize=50000&ignoreErrors=true&canonicalNaming=false ):

> java.lang.NoClassDefFoundError: com\/fasterxml\/jackson\/annotation\/JsonIgnoreProperties$Value

**Comment by gdubya** [comment]
Which traces it's way back to the fact that the project declares jackson 2.7.0 whereas Metrics requires > 2.8, so it's our own fault :)

After bumping jackson to 2.8.8 the hawtio Camel plugin works as expected.

**Comment by oscerd** [comment]
Maybe we can use Jackson 2.8.8 in hawtio too.

**Comment by gdubya** [comment]
Well, in my case the problem was server-side, in my application, rather than hawtio.

**Comment by oscerd** [comment]
By the way I'll investigate a bit about the jackson version
