### ISSUE TITLE
Karaf terminal does not work in Karaf 2.3.

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#931]
There is some recent API changes that breaks karaf 2.3.x

2014-01-12 12:39:55,763 | WARN  | qtp1767356747-62 | ServletHandler                   | pse.jetty.servlet.ServletHandler  539 | 58 - org.eclipse.jetty.util - 7.6.8.v20121106 | Error for /hawtio/hawtio-karaf-terminal/term
java.lang.NoSuchMethodError: org.apache.karaf.shell.console.jline.Console.<init>(Lorg/apache/felix/service/command/CommandProcessor;Lorg/apache/felix/service/threadio/ThreadIO;Ljava/io/InputStream;Ljava/io/PrintStream;Ljava/io/PrintStream;Ljline/Terminal;Ljava/lang/String;Ljava/lang/Runnable;)V
    at io.hawt.web.plugin.karaf.terminal.TerminalServlet$SessionTerminal.<init>(TerminalServlet.java:85)[88:io.hawt.hawtio-karaf-terminal:1.3.0.SNAPSHOT]
    at io.hawt.web.plugin.karaf.terminal.TerminalServlet.doPost(TerminalServlet.java:45)[88:io.hawt.hawtio-karaf-terminal:1.3.0.SNAPSHOT]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:713)[55:org.apache.geronimo.specs.geronimo-servlet_2.5_spec:1.2]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)[55:org.apache.geronimo.specs.geronimo-servlet_2.5_spec:1.2]
